export PATH="/well/lindgren/dpalmer/:$PATH"
cd /well/lindgren/UKBIOBANK/dpalmer/PRS_cell_data

# Choose reference panel:
RefPanel="data/HRC_variants/HRC.r1-1.GRCh37.wgs.mac5.sites.tab.gz"
export PATH="/well/lindgren/dpalmer/:$PATH"

plink --bfile data/combined/UKB_subset_combined --freq --out data/combined/UKB_subset_combined

# Run the check tool
perl HRC-1000G-check-bim.pl \
-b data/combined/UKB_subset_combined.bim \
-f data/combined/UKB_subset_combined.frq \
-t 0.2 \
-r ${RefPanel} -h

# The suggested plink commands generated by the tool are in this "Run-plink.sh" file
cd data/combined
head -n 5 Run-plink.sh
mv Run-plink.sh Run-plink-B37-ukb-combined.sh
bash Run-plink-B37-ukb-combined.sh

# The updated plink files
wc -l UKB_subset_combined-updated.bim

module purge
module load BCFtools/1.12-GCC-9.3.0

for chr in {1..23}
do
    bgzip -f UKB_subset_combined-updated-chr${chr}.vcf
done
